//
// Created by zr on 23-1-18.
//

#ifndef COMPRESS_MARKER_H
#define COMPRESS_MARKER_H

#define COMP_START_MARKER 0x5A52
#define COMP_FILE_MARKER 0x46
#define COMP_DIR_MARKER 0x44

#define NONE_COMPRESS_MARKER 0x4E
#define HUFFMAN_HEADER_MARKER 0x48
#define LZW_HEADER_MARKER 0x4C

#endif //COMPRESS_MARKER_H
